/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const VariantVariantIdLazyImport = createFileRoute('/variant/$variantId')()
const GeneGeneSymbolLazyImport = createFileRoute('/gene/$geneSymbol')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const VariantVariantIdLazyRoute = VariantVariantIdLazyImport.update({
  id: '/variant/$variantId',
  path: '/variant/$variantId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/variant.$variantId.lazy').then((d) => d.Route),
)

const GeneGeneSymbolLazyRoute = GeneGeneSymbolLazyImport.update({
  id: '/gene/$geneSymbol',
  path: '/gene/$geneSymbol',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/gene.$geneSymbol.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/gene/$geneSymbol': {
      id: '/gene/$geneSymbol'
      path: '/gene/$geneSymbol'
      fullPath: '/gene/$geneSymbol'
      preLoaderRoute: typeof GeneGeneSymbolLazyImport
      parentRoute: typeof rootRoute
    }
    '/variant/$variantId': {
      id: '/variant/$variantId'
      path: '/variant/$variantId'
      fullPath: '/variant/$variantId'
      preLoaderRoute: typeof VariantVariantIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/gene/$geneSymbol': typeof GeneGeneSymbolLazyRoute
  '/variant/$variantId': typeof VariantVariantIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/gene/$geneSymbol': typeof GeneGeneSymbolLazyRoute
  '/variant/$variantId': typeof VariantVariantIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/gene/$geneSymbol': typeof GeneGeneSymbolLazyRoute
  '/variant/$variantId': typeof VariantVariantIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gene/$geneSymbol' | '/variant/$variantId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gene/$geneSymbol' | '/variant/$variantId'
  id: '__root__' | '/' | '/gene/$geneSymbol' | '/variant/$variantId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  GeneGeneSymbolLazyRoute: typeof GeneGeneSymbolLazyRoute
  VariantVariantIdLazyRoute: typeof VariantVariantIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  GeneGeneSymbolLazyRoute: GeneGeneSymbolLazyRoute,
  VariantVariantIdLazyRoute: VariantVariantIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/gene/$geneSymbol",
        "/variant/$variantId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/gene/$geneSymbol": {
      "filePath": "gene.$geneSymbol.lazy.tsx"
    },
    "/variant/$variantId": {
      "filePath": "variant.$variantId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
