/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const VariantVariantIdLazyImport = createFileRoute('/variant/$variantId')()

// Create/Update Routes

const VariantVariantIdLazyRoute = VariantVariantIdLazyImport.update({
  id: '/variant/$variantId',
  path: '/variant/$variantId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/variant.$variantId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/variant/$variantId': {
      id: '/variant/$variantId'
      path: '/variant/$variantId'
      fullPath: '/variant/$variantId'
      preLoaderRoute: typeof VariantVariantIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/variant/$variantId': typeof VariantVariantIdLazyRoute
}

export interface FileRoutesByTo {
  '/variant/$variantId': typeof VariantVariantIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/variant/$variantId': typeof VariantVariantIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/variant/$variantId'
  fileRoutesByTo: FileRoutesByTo
  to: '/variant/$variantId'
  id: '__root__' | '/variant/$variantId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  VariantVariantIdLazyRoute: typeof VariantVariantIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  VariantVariantIdLazyRoute: VariantVariantIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/variant/$variantId"
      ]
    },
    "/variant/$variantId": {
      "filePath": "variant.$variantId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
